/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Controller.CRUD;
import Components.Functions;
import Models.Categoria_Documentos;
import Models.Centrales;
import Models.Documentos;
import Models.Equipos_Gen;
import Models.Estado_Documentos;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ELSO
 */
public class AddDocumentsApp extends JDialog {

    /**
     * Creates new form AddDocumentApp
     */
    /*Instancias de Objetos*/
    Functions Estados = new Functions();
    CRUD cargarCombos = new CRUD();
    Documentos Documento = new Documentos();
    Estado_Documentos Status = new Estado_Documentos();
    Categoria_Documentos Catego = new Categoria_Documentos();

    /* === VARIABLES PARA FOREING KEYS ==*/
    int Id_Central = 0;
    int Id_Equipo = 0;
    int Id_CategoriaDoc = 0;
    int Id_Estado = 0;

    public AddDocumentsApp() {
        initComponents();
    }

    public AddDocumentsApp(List_Documents AddDocumentPT, boolean modal) {
        super(AddDocumentPT, modal);
        initComponents();
        this.setSize(1280, 680);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("MÓDULO DE REGISTROS DE DOCUMENTOS DE TRABAJOS");
        Estados.DesactivarJText(JPanel_Body);
        DefaultComboBoxModel modCentral = new DefaultComboBoxModel(cargarCombos.cargarCentrales());
        DefaultComboBoxModel modEstado = new DefaultComboBoxModel(cargarCombos.cargarEstadosDocumentos(Status.getId_Estado()));
        DefaultComboBoxModel modCategoria = new DefaultComboBoxModel(cargarCombos.cargarCatergoriaDocumentos(Catego.getId_CategoriaD()));
        JCombo_Central.setModel(modCentral);
        JCombo_Estado.setModel(modEstado);
        JCombo_Tipo.setModel(modCategoria);
    }

    private void restaurarFormularios() {
        JCombo_Descripcion.setSelectedItem("SELECCIONA UNA CATEGORÍA");
        Numero_Gen.setText(null);
        Fecha_Vigencia_Text.setDate(null);
        Fecha_Caduca_Text.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_Body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Central_Label = new javax.swing.JLabel();
        N_Equipo_Label = new javax.swing.JLabel();
        N_Documento_Label = new javax.swing.JLabel();
        Tipo_Trabajo_Label = new javax.swing.JLabel();
        Descripcion_Label = new javax.swing.JLabel();
        Central_Label8 = new javax.swing.JLabel();
        Fecha_Vigencia_Label = new javax.swing.JLabel();
        Fecha_Caducacion_Label = new javax.swing.JLabel();
        JCombo_Central = new javax.swing.JComboBox<>();
        JCombo_Equipo = new javax.swing.JComboBox<>();
        Numero_Gen = new javax.swing.JTextField();
        JCombo_Tipo = new javax.swing.JComboBox<>();
        JCombo_Descripcion = new javax.swing.JComboBox<>();
        Fecha_Vigencia_Text = new com.toedter.calendar.JDateChooser();
        Fecha_Caduca_Text = new com.toedter.calendar.JDateChooser();
        JCombo_Estado = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        Btn_Nuevo = new rojeru_san.RSButton();
        Btn_Guardar = new rojeru_san.RSButton();
        JPanelBottom = new javax.swing.JPanel();
        Banner_Header_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel_Body.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("PANEL DE CONTROL");

        Titulo1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(51, 51, 51));
        Titulo1.setText("FORMULARIO DE REGISTRO PARA FAENAS DE MANTENIMIENTOS");

        Central_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Central_Label.setForeground(new java.awt.Color(102, 102, 102));
        Central_Label.setText("CENTRAL:");

        N_Equipo_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        N_Equipo_Label.setForeground(new java.awt.Color(102, 102, 102));
        N_Equipo_Label.setText("N° EQUIPO:");

        N_Documento_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        N_Documento_Label.setForeground(new java.awt.Color(102, 102, 102));
        N_Documento_Label.setText("N° DOCUMENTO:");

        Tipo_Trabajo_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Tipo_Trabajo_Label.setForeground(new java.awt.Color(102, 102, 102));
        Tipo_Trabajo_Label.setText("TIPO DE TRABAJO:");

        Descripcion_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Descripcion_Label.setForeground(new java.awt.Color(102, 102, 102));
        Descripcion_Label.setText("DESCRIPCIÓN:");

        Central_Label8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Central_Label8.setForeground(new java.awt.Color(102, 102, 102));
        Central_Label8.setText("ESTADO DEL DOCUMENTO:");

        Fecha_Vigencia_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Fecha_Vigencia_Label.setForeground(new java.awt.Color(102, 102, 102));
        Fecha_Vigencia_Label.setText("FECHA DE VIGENCIA:");

        Fecha_Caducacion_Label.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Fecha_Caducacion_Label.setForeground(new java.awt.Color(102, 102, 102));
        Fecha_Caducacion_Label.setText("FECHA CADUCACIÓN:");

        JCombo_Central.setBackground(new java.awt.Color(255, 255, 255));
        JCombo_Central.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JCombo_Central.setForeground(new java.awt.Color(51, 51, 51));
        JCombo_Central.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA CENTRAL" }));
        JCombo_Central.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCombo_CentralItemStateChanged(evt);
            }
        });

        JCombo_Equipo.setBackground(new java.awt.Color(255, 255, 255));
        JCombo_Equipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JCombo_Equipo.setForeground(new java.awt.Color(51, 51, 51));
        JCombo_Equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UN EQUIPO" }));
        JCombo_Equipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCombo_EquipoItemStateChanged(evt);
            }
        });

        Numero_Gen.setBackground(new java.awt.Color(255, 255, 255));
        Numero_Gen.setForeground(new java.awt.Color(51, 51, 51));
        Numero_Gen.setBorder(null);
        Numero_Gen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Numero_GenKeyTyped(evt);
            }
        });

        JCombo_Tipo.setBackground(new java.awt.Color(255, 255, 255));
        JCombo_Tipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JCombo_Tipo.setForeground(new java.awt.Color(51, 51, 51));
        JCombo_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UN TIPO DE DOCUMENTO" }));
        JCombo_Tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCombo_TipoItemStateChanged(evt);
            }
        });

        JCombo_Descripcion.setBackground(new java.awt.Color(255, 255, 255));
        JCombo_Descripcion.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JCombo_Descripcion.setForeground(new java.awt.Color(51, 51, 51));
        JCombo_Descripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA CATEGORÍA", "CAMBIO DE ACEITE, FILTROS Y LIMPIEZA RADIADOR", "CAMBIO DE REFRIGERANTE Y LIMPIEZA RADIADOR", "CAMBIO DE FILTROS RACOR COMBUSTIBLE", "CAMBIO DE FILTRO DE AIRE", "CAMBIO DE CORREAS VENTILADOR RADIADOR", "CAMBIO DE BATERÍAS", "CAMBIO DE CORREAS ALTERNADOR", "CAMBIO DE MANTENEDOR DE BATERÍAS", "CAMBIO DE BORNES DE BATERÍAS", "MEDICIÓN VOLTAJE DE BATERÍAS", "CAMBIO DE BISAGRAS PUERTAS CONTAINER", "CAMBIO LUMINARIAS CONTAINER" }));

        Fecha_Vigencia_Text.setBackground(new java.awt.Color(255, 255, 255));
        Fecha_Vigencia_Text.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Fecha_Vigencia_Text.setForeground(new java.awt.Color(51, 51, 51));
        Fecha_Vigencia_Text.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        Fecha_Caduca_Text.setBackground(new java.awt.Color(255, 255, 255));
        Fecha_Caduca_Text.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Fecha_Caduca_Text.setForeground(new java.awt.Color(51, 51, 51));
        Fecha_Caduca_Text.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        JCombo_Estado.setBackground(new java.awt.Color(255, 255, 255));
        JCombo_Estado.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JCombo_Estado.setForeground(new java.awt.Color(51, 51, 51));
        JCombo_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UN ESTADO" }));
        JCombo_Estado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCombo_EstadoItemStateChanged(evt);
            }
        });

        Btn_Nuevo.setBackground(new java.awt.Color(0, 153, 51));
        Btn_Nuevo.setText("NUEVO");
        Btn_Nuevo.setColorHover(new java.awt.Color(0, 102, 0));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Guardar.setBackground(new java.awt.Color(0, 102, 204));
        Btn_Guardar.setText("GUARDAR");
        Btn_Guardar.setColorHover(new java.awt.Color(0, 51, 255));
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_BodyLayout = new javax.swing.GroupLayout(JPanel_Body);
        JPanel_Body.setLayout(JPanel_BodyLayout);
        JPanel_BodyLayout.setHorizontalGroup(
            JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_BodyLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                        .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                        .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_BodyLayout.createSequentialGroup()
                                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(N_Equipo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Central_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Central_Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JCombo_Central, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCombo_Equipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCombo_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addGap(386, 386, 386)))
                                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(JPanel_BodyLayout.createSequentialGroup()
                                            .addComponent(Tipo_Trabajo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCombo_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPanel_BodyLayout.createSequentialGroup()
                                            .addComponent(Descripcion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCombo_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_BodyLayout.createSequentialGroup()
                                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Fecha_Caducacion_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(N_Documento_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Fecha_Vigencia_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Numero_Gen, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Fecha_Vigencia_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Fecha_Caduca_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(139, 139, 139))))
        );
        JPanel_BodyLayout.setVerticalGroup(
            JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_BodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Titulo1)
                .addGap(36, 36, 36)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCombo_Central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Central_Label)
                    .addComponent(Tipo_Trabajo_Label)
                    .addComponent(JCombo_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N_Equipo_Label)
                    .addComponent(JCombo_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion_Label)
                    .addComponent(JCombo_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N_Documento_Label)
                    .addComponent(Numero_Gen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Central_Label8)
                    .addComponent(JCombo_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha_Vigencia_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_Vigencia_Label))
                .addGap(18, 18, 18)
                .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                        .addGroup(JPanel_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha_Caduca_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha_Caducacion_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(JPanel_BodyLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(JPanel_Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 1280, 460));

        JPanelBottom.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout JPanelBottomLayout = new javax.swing.GroupLayout(JPanelBottom);
        JPanelBottom.setLayout(JPanelBottomLayout);
        JPanelBottomLayout.setHorizontalGroup(
            JPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        JPanelBottomLayout.setVerticalGroup(
            JPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(JPanelBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1280, 90));

        Banner_Header_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BG-PT.png"))); // NOI18N
        Banner_Header_Label.setText("Banner_Header");
        getContentPane().add(Banner_Header_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        if (JCombo_Central.getSelectedItem().equals("SELECCIONA UNA CENTRAL")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UNA CENTRAL PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (JCombo_Equipo.getSelectedItem().equals("SELECCIONA UN EQUIPO")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UNA EQUIPO PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (JCombo_Estado.getSelectedItem().equals("SELECCIONA UN ESTADO")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UN ESTADO PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (JCombo_Tipo.getSelectedItem().equals("SELECCIONA UN TIPO DE DOCUMENTO")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UN TIPO DE DOCUMENTO PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (JCombo_Descripcion.getSelectedItem().equals("SELECCIONA UN CATEGORÍA")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UNA CATEGORÍA PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (Numero_Gen.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES INGRESAR UN NUMERO DE DOCUMENTO PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (Fecha_Vigencia_Text.getDate() == null) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UNA FECHA DE INICIO PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (Fecha_Caduca_Text.getDate() == null) {
            JOptionPane.showMessageDialog(null, "POR FAVOR, DEBES SELECCIONAR UNA FECHA DE CADUCACIÓN PARA CONTINUAR", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            /*== METODO SETTER Y GETTER DEL MODELO ==*/
            Catego.setNumero(Numero_Gen.getText());
            Catego.setDescripcion(JCombo_Descripcion.getSelectedItem().toString());
            Catego.setVigencia(Estados.formatoFecha(Fecha_Vigencia_Text));
            Catego.setTermino(Estados.formatoFecha(Fecha_Caduca_Text));
            Catego.setId_Equipo(Id_Equipo);
            Catego.setId_Central(Id_Central);
            Catego.setId_CategoriaD(Id_CategoriaDoc);
            Status.setId_Estado(Id_Estado);

            /*=== FUNCION PARA REGISTRAR UN NUEVO DOCUMENTO ===*/
            cargarCombos.guardarDocumentosT(Catego, Status, JPanel_Body, Numero_Gen);
            DefaultComboBoxModel modCentral = new DefaultComboBoxModel(cargarCombos.cargarCentrales());
            DefaultComboBoxModel modEstado = new DefaultComboBoxModel(cargarCombos.cargarEstadosDocumentos(Status.getId_Estado()));
            DefaultComboBoxModel modCategoria = new DefaultComboBoxModel(cargarCombos.cargarCatergoriaDocumentos(Catego.getId_CategoriaD()));
             DefaultComboBoxModel modEquipo = new DefaultComboBoxModel(cargarCombos.cargarEquipos(Catego.getId_Central()));
            JCombo_Equipo.setModel(modEquipo);
            JCombo_Central.setModel(modCentral);
            JCombo_Estado.setModel(modEstado);
            JCombo_Tipo.setModel(modCategoria);
            restaurarFormularios();
        }
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        // TODO add your handling code here:
        Estados.ActivarJText(JPanel_Body);
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void JCombo_CentralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCombo_CentralItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Centrales Equipo = (Centrales) JCombo_Central.getSelectedItem();
            DefaultComboBoxModel modEquipo = new DefaultComboBoxModel(cargarCombos.cargarEquipos(Equipo.getId_Central()));
            JCombo_Equipo.setModel(modEquipo);
            Id_Central = Equipo.getId_Central();
            System.out.println("El Id de la Central es: " + Id_Central);

        }

    }//GEN-LAST:event_JCombo_CentralItemStateChanged

    private void JCombo_EquipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCombo_EquipoItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Equipos_Gen Equipo = (Equipos_Gen) JCombo_Equipo.getSelectedItem();
            Id_Equipo = Equipo.getId_Equipo();
            System.out.println("El Id del Equipo es: " + Id_Equipo);

        }
    }//GEN-LAST:event_JCombo_EquipoItemStateChanged

    private void JCombo_EstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCombo_EstadoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Estado_Documentos Estado = (Estado_Documentos) JCombo_Estado.getSelectedItem();
            Id_Estado = Estado.getId_Estado();
            System.out.println("El Id Seleccionado del Estado Documento es: " + Id_Estado);

        }
    }//GEN-LAST:event_JCombo_EstadoItemStateChanged

    private void JCombo_TipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCombo_TipoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Categoria_Documentos Tipo = (Categoria_Documentos) JCombo_Tipo.getSelectedItem();
            Id_CategoriaDoc = Tipo.getId_CategoriaD();
            System.out.println("El Id Seleccionado Correspondiente a la Categoria del Documento es: " + Id_CategoriaDoc);

        }
    }//GEN-LAST:event_JCombo_TipoItemStateChanged

    private void Numero_GenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Numero_GenKeyTyped
        char a = evt.getKeyChar();
        if (a == KeyEvent.VK_ENTER) {
            JCombo_Descripcion.requestFocus();
        }
    }//GEN-LAST:event_Numero_GenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDocumentsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDocumentsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDocumentsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDocumentsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDocumentsApp dialog = new AddDocumentsApp((List_Documents) new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner_Header_Label;
    private rojeru_san.RSButton Btn_Guardar;
    private rojeru_san.RSButton Btn_Nuevo;
    private javax.swing.JLabel Central_Label;
    private javax.swing.JLabel Central_Label8;
    private javax.swing.JLabel Descripcion_Label;
    private com.toedter.calendar.JDateChooser Fecha_Caduca_Text;
    private javax.swing.JLabel Fecha_Caducacion_Label;
    private javax.swing.JLabel Fecha_Vigencia_Label;
    private com.toedter.calendar.JDateChooser Fecha_Vigencia_Text;
    private javax.swing.JComboBox<String> JCombo_Central;
    private javax.swing.JComboBox<String> JCombo_Descripcion;
    private javax.swing.JComboBox<String> JCombo_Equipo;
    private javax.swing.JComboBox<String> JCombo_Estado;
    private javax.swing.JComboBox<String> JCombo_Tipo;
    private javax.swing.JPanel JPanelBottom;
    private javax.swing.JPanel JPanel_Body;
    private javax.swing.JLabel N_Documento_Label;
    private javax.swing.JLabel N_Equipo_Label;
    private javax.swing.JTextField Numero_Gen;
    private javax.swing.JLabel Tipo_Trabajo_Label;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
