/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Components.Functions;
import Models.Users;

/**
 *
 * @author ELSO
 */
public class DashboardApp extends javax.swing.JFrame {

    //Variables Públicas para Formularios
    public static DashboardApp JDashboardApp;
    public static List_Documents JForm_List_PT;
    public static UpdateDocumentsApp Form_Update;
    public static ProductionReportsApp JForm_Report;

    /*== INSTANCIAS DE OBJETOS ==*/
    Users accesoUsuarios = new Users();

    /**
     * Creates new form DashboardApp
     */
    public DashboardApp() {
        initComponents();
        this.setSize(1920, 1080);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("PLATAFORMA DE GESTIÓN - DASHBOARD - MODO DESARROLLO");

    }

    public DashboardApp(Users accesoUsuarios) {
        initComponents();
        this.setSize(1920, 1080);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("PLATAFORMA DE GESTIÓN - DASHBOARD");

        this.accesoUsuarios = accesoUsuarios;
        JUser.setText(accesoUsuarios.getUsuario());
        JRol.setText(accesoUsuarios.getRol());

        switch (accesoUsuarios.getTipoUsuario()) {
            case 1:
                /*== SE CARGA MÓDULO COMPLETO DEL ADMINISTRADOR ==*/                
                break;
                
            case 2:
                /*== SE CARGA MÓDULO COMPLETO DEL SUPERVISOR ==*/                
                break;
                
            case 3:
                /*== SE CARGA MÓDULO COMPLETO DEL USUARIO ==*/  
                break;
                
            case 4:
                /*== SE CARGA MÓDULO COMPLETO DEL INVITADO ==*/
                JMenu_Mantenimientos.setVisible(false);
                JMenu_Estado_PT.setVisible(false);
                JMenu_Reports_PT.setVisible(false);
                JMenu_Informes.setVisible(false);
                JMenu_Reports_Gx.setVisible(false);
                JMenu_Personal.setVisible(false);
                JMenu_Epp.setVisible(false);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JIcon = new javax.swing.JLabel();
        JConectado = new javax.swing.JLabel();
        JUsername = new javax.swing.JLabel();
        JUsername1 = new javax.swing.JLabel();
        JUser = new javax.swing.JLabel();
        JRol = new javax.swing.JLabel();
        JBackground_Principal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_Inicio = new javax.swing.JMenu();
        BtnLogout = new javax.swing.JMenuItem();
        BtnExit = new javax.swing.JMenuItem();
        JMenu_Mantenimientos = new javax.swing.JMenu();
        JMenu_AddPT = new javax.swing.JMenuItem();
        JMenu_Estado_PT = new javax.swing.JMenuItem();
        JMenu_Reports_PT = new javax.swing.JMenuItem();
        JMenu_Informes = new javax.swing.JMenu();
        JMenu_Cierre = new javax.swing.JMenuItem();
        JMenu_Reports_Gx = new javax.swing.JMenuItem();
        JMenuGP = new javax.swing.JMenu();
        JMenu_Personal = new javax.swing.JMenuItem();
        JMenu_Epp = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        JIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/man.png"))); // NOI18N

        JConectado.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        JConectado.setForeground(new java.awt.Color(0, 255, 0));
        JConectado.setText("CONECTADO");

        JUsername.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        JUsername.setForeground(new java.awt.Color(255, 255, 255));
        JUsername.setText("Usuario en Línea:");

        JUsername1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        JUsername1.setForeground(new java.awt.Color(255, 255, 255));
        JUsername1.setText("Rol de Usuario:");

        JUser.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        JUser.setForeground(new java.awt.Color(255, 153, 0));
        JUser.setText("Nombre");

        JRol.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        JRol.setForeground(new java.awt.Color(255, 102, 0));
        JRol.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JIcon)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(JConectado))
                    .addComponent(JUsername))
                .addGap(22, 22, 22)
                .addComponent(JUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(JUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JRol, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JIcon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(JConectado)
                        .addGap(16, 16, 16)
                        .addComponent(JUsername))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JUser)
                            .addComponent(JUsername1)
                            .addComponent(JRol))))
                .addGap(76, 76, 76))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 1920, 210));

        JBackground_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BG-Bashboard-1080p.png"))); // NOI18N
        getContentPane().add(JBackground_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1040));

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N

        JMenu_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/homeregular_32x32.png"))); // NOI18N
        JMenu_Inicio.setText("INICIO");
        JMenu_Inicio.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N

        BtnLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        BtnLogout.setText("CERRAR SESIÓN");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        JMenu_Inicio.add(BtnLogout);

        BtnExit.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        BtnExit.setText("SALIR DEL SISTEMA");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        JMenu_Inicio.add(BtnExit);

        jMenuBar1.add(JMenu_Inicio);

        JMenu_Mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/maintenance256_24835.png"))); // NOI18N
        JMenu_Mantenimientos.setText("GESTIÓN MANTENIMIENTO");
        JMenu_Mantenimientos.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N

        JMenu_AddPT.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_AddPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enviando.png"))); // NOI18N
        JMenu_AddPT.setText("DOCUMENTOS DE TRABAJO");
        JMenu_AddPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_AddPTActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenu_AddPT);

        JMenu_Estado_PT.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Estado_PT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documentos.png"))); // NOI18N
        JMenu_Estado_PT.setText("ESTADO DE MANTENIMIENTO");
        JMenu_Mantenimientos.add(JMenu_Estado_PT);

        JMenu_Reports_PT.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Reports_PT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/informe-seo.png"))); // NOI18N
        JMenu_Reports_PT.setText("REPORTES Y ESTADISTICAS");
        JMenu_Mantenimientos.add(JMenu_Reports_PT);

        jMenuBar1.add(JMenu_Mantenimientos);

        JMenu_Informes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/informe-seo.png"))); // NOI18N
        JMenu_Informes.setText("GESTIÓN INFORMES");
        JMenu_Informes.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N

        JMenu_Cierre.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Cierre.setText("CIERRE DE MES");
        JMenu_Cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_CierreActionPerformed(evt);
            }
        });
        JMenu_Informes.add(JMenu_Cierre);

        JMenu_Reports_Gx.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Reports_Gx.setText("REPORTES Y ESTADISTICAS");
        JMenu_Informes.add(JMenu_Reports_Gx);

        jMenuBar1.add(JMenu_Informes);

        JMenuGP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_folder_20282.png"))); // NOI18N
        JMenuGP.setText("GESTION PERSONAL");
        JMenuGP.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N

        JMenu_Personal.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Personal.setText("NÓMINA DE PERSONAL");
        JMenuGP.add(JMenu_Personal);

        JMenu_Epp.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        JMenu_Epp.setText("ENTREGA DE EPP");
        JMenuGP.add(JMenu_Epp);

        jMenuBar1.add(JMenuGP);

        jMenu1.setText("ACERCA");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        Functions logout = new Functions();
        LoginApp Login = new LoginApp();
        logout.cerrarSesion(this, Login);
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void JMenu_AddPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_AddPTActionPerformed
        // TODO add your handling code here:
        try {

            List_Documents JForm_List = new List_Documents(this, true);
            JForm_List.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_JMenu_AddPTActionPerformed

    private void JMenu_CierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_CierreActionPerformed
        // TODO add your handling code here:
        try {

            ProductionReportsApp JForm_Report = new ProductionReportsApp(this, true);
            JForm_Report.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JMenu_CierreActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        Functions Event = new Functions();
        Event.confirmarSalida();
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnExit;
    private javax.swing.JMenuItem BtnLogout;
    private javax.swing.JLabel JBackground_Principal;
    private javax.swing.JLabel JConectado;
    private javax.swing.JLabel JIcon;
    private javax.swing.JMenu JMenuGP;
    private javax.swing.JMenuItem JMenu_AddPT;
    private javax.swing.JMenuItem JMenu_Cierre;
    private javax.swing.JMenuItem JMenu_Epp;
    private javax.swing.JMenuItem JMenu_Estado_PT;
    private javax.swing.JMenu JMenu_Informes;
    private javax.swing.JMenu JMenu_Inicio;
    private javax.swing.JMenu JMenu_Mantenimientos;
    private javax.swing.JMenuItem JMenu_Personal;
    private javax.swing.JMenuItem JMenu_Reports_Gx;
    private javax.swing.JMenuItem JMenu_Reports_PT;
    private javax.swing.JLabel JRol;
    private javax.swing.JLabel JUser;
    private javax.swing.JLabel JUsername;
    private javax.swing.JLabel JUsername1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
