/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Controller.CRUD;
import Components.Functions;
import Models.Categoria_Documentos;
import Models.Estado_Documentos;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ELSO
 */
public class List_Documents extends JDialog {

    /**
     * Creates new form List_Documents
     *
     *
     */
    public static UpdateDocumentsApp Form_Update;
    Functions Evento = new Functions();
    CRUD Consulta = new CRUD();
    Categoria_Documentos Documento = new Categoria_Documentos();
    Estado_Documentos Estado = new Estado_Documentos();

    public List_Documents() {
        initComponents();
    }

    public List_Documents(DashboardApp List_Documents_PT, boolean modal) {
        super(List_Documents_PT, modal);
        initComponents();
        this.setSize(1366, 768);
        this.setLocationRelativeTo(null);
        this.setTitle("PLATAFORMA DE GESTIÓN - MÓDULO DE REGISTRO DE DOCUMENTOS DE TRABAJO");
        Consulta.cargarDocumentos(JTable_PT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_Header = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_PT = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPBtn_Crud = new javax.swing.JPanel();
        Btn_Update = new rojeru_san.RSButton();
        Btn_Cambiar = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        Buscar_Text = new rojeru_san.RSMTextFull();
        JPBtn_Add = new javax.swing.JPanel();
        JBtn_Agregar_PT = new rojeru_san.RSButton();
        JLabelInfo = new javax.swing.JLabel();
        BG_LIST = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel_Header.setBackground(new java.awt.Color(255, 255, 255));

        JTable_PT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JTable_PT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTable_PT.setColorBackgoundHead(new java.awt.Color(22, 99, 212));
        JTable_PT.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        JTable_PT.setColorBordeHead(new java.awt.Color(255, 255, 255));
        JTable_PT.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        JTable_PT.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        JTable_PT.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        JTable_PT.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        JTable_PT.setColorSelForeground(new java.awt.Color(51, 51, 51));
        JTable_PT.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        JTable_PT.setFuenteFilas(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        JTable_PT.setFuenteFilasSelect(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JTable_PT.setFuenteHead(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        JTable_PT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_PTMouseClicked(evt);
            }
        });
        JTable_PT.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                JTable_PTComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_PT);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("LISTADO DE REGISTROS DE DOCUMENTOS DE TRABAJO");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("FILTRO DE BUSQUEDA");

        JPBtn_Crud.setBackground(new java.awt.Color(255, 255, 255));

        Btn_Update.setBackground(new java.awt.Color(255, 153, 0));
        Btn_Update.setBorder(null);
        Btn_Update.setText("ACTUALIZAR");
        Btn_Update.setColorHover(new java.awt.Color(204, 102, 0));
        Btn_Update.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Cambiar.setBackground(new java.awt.Color(0, 153, 153));
        Btn_Cambiar.setBorder(null);
        Btn_Cambiar.setText("CAMBIAR ESTADO");
        Btn_Cambiar.setColorHover(new java.awt.Color(0, 102, 102));
        Btn_Cambiar.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        Btn_Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CambiarActionPerformed(evt);
            }
        });

        rSButton3.setBackground(new java.awt.Color(255, 0, 0));
        rSButton3.setBorder(null);
        rSButton3.setText("ELIMINAR");
        rSButton3.setColorHover(new java.awt.Color(204, 0, 51));
        rSButton3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N

        javax.swing.GroupLayout JPBtn_CrudLayout = new javax.swing.GroupLayout(JPBtn_Crud);
        JPBtn_Crud.setLayout(JPBtn_CrudLayout);
        JPBtn_CrudLayout.setHorizontalGroup(
            JPBtn_CrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBtn_CrudLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JPBtn_CrudLayout.setVerticalGroup(
            JPBtn_CrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBtn_CrudLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(JPBtn_CrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Buscar_Text.setBackground(new java.awt.Color(255, 255, 255));
        Buscar_Text.setForeground(new java.awt.Color(102, 102, 102));
        Buscar_Text.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        Buscar_Text.setPlaceholder("Escribe aqui...................");
        Buscar_Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Buscar_TextKeyPressed(evt);
            }
        });

        JPBtn_Add.setBackground(new java.awt.Color(255, 255, 255));

        JBtn_Agregar_PT.setBackground(new java.awt.Color(0, 153, 0));
        JBtn_Agregar_PT.setBorder(null);
        JBtn_Agregar_PT.setText("AGREGAR");
        JBtn_Agregar_PT.setColorHover(new java.awt.Color(0, 102, 0));
        JBtn_Agregar_PT.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        JBtn_Agregar_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_Agregar_PTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPBtn_AddLayout = new javax.swing.GroupLayout(JPBtn_Add);
        JPBtn_Add.setLayout(JPBtn_AddLayout);
        JPBtn_AddLayout.setHorizontalGroup(
            JPBtn_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBtn_AddLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(JBtn_Agregar_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        JPBtn_AddLayout.setVerticalGroup(
            JPBtn_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBtn_AddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtn_Agregar_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        JLabelInfo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N

        javax.swing.GroupLayout JPanel_HeaderLayout = new javax.swing.GroupLayout(JPanel_Header);
        JPanel_Header.setLayout(JPanel_HeaderLayout);
        JPanel_HeaderLayout.setHorizontalGroup(
            JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_HeaderLayout.createSequentialGroup()
                .addGroup(JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_HeaderLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JPBtn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPBtn_Crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(JPanel_HeaderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelInfo))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        JPanel_HeaderLayout.setVerticalGroup(
            JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_HeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JPBtn_Crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPBtn_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JLabelInfo)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        getContentPane().add(JPanel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1370, 720));

        BG_LIST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BG-ListDocuments.png"))); // NOI18N
        getContentPane().add(BG_LIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_Agregar_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_Agregar_PTActionPerformed
        // TODO add your handling code here:

        try {
            AddDocumentsApp JForm_AddPT = new AddDocumentsApp(this, true);
            AddDocumentsApp.Btn_Update.setVisible(false);
            JForm_AddPT.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_JBtn_Agregar_PTActionPerformed

    private void JTable_PTComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JTable_PTComponentResized
        JTable_PT.getColumnModel().getColumn(0).setPreferredWidth(50);
        JTable_PT.getColumnModel().getColumn(1).setPreferredWidth(50);
        JTable_PT.getColumnModel().getColumn(2).setPreferredWidth(50);
        JTable_PT.getColumnModel().getColumn(3).setPreferredWidth(50);
        JTable_PT.getColumnModel().getColumn(4).setPreferredWidth(50);
        JTable_PT.getColumnModel().getColumn(5).setPreferredWidth(100);
        JTable_PT.getColumnModel().getColumn(6).setPreferredWidth(150);
        JTable_PT.getColumnModel().getColumn(7).setPreferredWidth(90);
    }//GEN-LAST:event_JTable_PTComponentResized

    private void JTable_PTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_PTMouseClicked
        try {
            int Fila = JTable_PT.rowAtPoint(evt.getPoint());
            //Documento.setCentral(JTable_PT.getValueAt(Fila, 0).toString());
            //Documento.setNumero(JTable_PT.getValueAt(Fila, 1).toString());
            //Documento.setNumero_Doc(JTable_PT.getValueAt(Fila, 2).toString());
            //UpdateDocumentsApp.JComboCentral.setSelectedItem(Documento.getCentral());
            UpdateDocumentsApp.JComboCentral.setSelectedItem(String.valueOf(JTable_PT.getValueAt(Fila, 0).toString()));
            UpdateDocumentsApp.JComboEstado.setSelectedItem(String.valueOf(JTable_PT.getValueAt(Fila, 7).toString()));
            //UpdateDocumentsApp.JComboEquipo.setSelectedItem(Documento.getNumero());
            UpdateDocumentsApp.Numero_Gen.setText(Documento.getNumero_Doc());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO UNA FILA", "ADVERTENCIA" + e, JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_JTable_PTMouseClicked

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed

        try {
            UpdateDocumentsApp UpdateForm = new UpdateDocumentsApp(this, true);
            AddDocumentsApp EditForm = new AddDocumentsApp(this, true);
            int Fila = JTable_PT.getSelectedRow();
            if (Fila == -1) {
                JOptionPane.showMessageDialog(null, "POR FAVOR, SELECCIONA UN REGISTRO PARA ACTUALIZAR", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                AddDocumentsApp.Btn_Guardar.setVisible(false);
                EditForm.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Buscar_TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Buscar_TextKeyPressed
        Documento.setBuscar(Buscar_Text.getText());
        if (Consulta.busquedaDocTabla(Documento, JTable_PT)) {
            //JLabelInfo.setText("SE ENCONTRARON DATOS EN SU BUSQUEDA");
        } else {
            JLabelInfo.setText("NO SE ENCONTRARON COINCIDENCIAS EN LA BUSQUEDA");
        }
    }//GEN-LAST:event_Buscar_TextKeyPressed

    private void Btn_CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CambiarActionPerformed
        int Fila = JTable_PT.getSelectedRow();
        try {
            UpdateDocumentsApp UpdateForm = new UpdateDocumentsApp(this, true);
            if (Fila == -1) {
                JOptionPane.showMessageDialog(null, "POR FAVOR, SELECCIONA UN REGISTRO PARA CAMBIAR EL ESTADO DEL DOCUMENTO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {

                Documento.setCentral(JTable_PT.getValueAt(Fila, 0).toString());
                Documento.setNumero(JTable_PT.getValueAt(Fila, 1).toString());
                Documento.setNumero_Doc(JTable_PT.getValueAt(Fila, 2).toString());

                UpdateDocumentsApp.JComboCentral.setSelectedItem(Documento.getCentral());
                UpdateDocumentsApp.JComboEquipo.setSelectedItem(Documento.getNumero());
                UpdateDocumentsApp.Numero_Gen.setText(Documento.getNumero_Doc());

                System.out.println(Documento.getCentral());
                UpdateForm.setVisible(true);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_CambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Documents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Documents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Documents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Documents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List_Documents dialog = new List_Documents((DashboardApp) new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_LIST;
    private rojeru_san.RSButton Btn_Cambiar;
    private rojeru_san.RSButton Btn_Update;
    private rojeru_san.RSMTextFull Buscar_Text;
    private rojeru_san.RSButton JBtn_Agregar_PT;
    private javax.swing.JLabel JLabelInfo;
    private javax.swing.JPanel JPBtn_Add;
    private javax.swing.JPanel JPBtn_Crud;
    private javax.swing.JPanel JPanel_Header;
    public static rojerusan.RSTableMetro JTable_PT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton rSButton3;
    // End of variables declaration//GEN-END:variables
}
