/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.AUTH;
import Components.Functions;
import Models.Users;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ELSO
 */
public class LoginApp extends javax.swing.JFrame {

    /**
     * Creates new form LoginApp
     */
    public LoginApp() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        TextUser.requestFocus();
    }
    
    /*===  METODO DE AUTENTIFICACIÓN DE USUARIOS "LOGIN DE USUARIOS" ====*/
    protected void iniciarSesion(){
        /* == OBJETOS DE CLASE ==*/
        Users Validar = new Users();
        AUTH Acceso = new AUTH();
        Date Fecha = new Date();
        DateFormat Historial = new SimpleDateFormat ("yyyy-MM-dd HH.mm:ss");
        
        String claveAcceso = new String (TextPassword.getPassword());
        
        /*== VÁLIDACIÓN DE DATOS PARA ACCESO DE USUARIOS ==*/
        if (TextUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, Ingrese un nombre de usuario", "Información", JOptionPane.INFORMATION_MESSAGE);
            
        } else if (claveAcceso.equals("")){            
          JOptionPane.showMessageDialog(null, "Por favor, Ingresa contraseña", "Información", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            /* == RECIBIMOS LOS PARAMETROS DEL MODELO  DE DATOS ==*/
            Validar.setUsuario(TextUser.getText());
            Validar.setClave(TextPassword.getText());
            Validar.setSesion(Historial.format(Fecha));
            
            /*== CONDICIONAL PARA ACCESO DEL USUARIO ==*/
            if (Acceso.Auth_User(Validar)){
                /*== CONCEDEMOS ACCESO DEL USUARIO ==*/
                JOptionPane.showMessageDialog(null, "El Nombre de Usuario y la Contraseña son Correctos", "Inicio de Sesión Existosa", JOptionPane.INFORMATION_MESSAGE);
                DashboardApp Home = new DashboardApp(Validar);
                this.setVisible(false);
                Home.setVisible(true);
                
            } else {
                /*== ARROGAMOS UN ERROR DE LOGEO ==*/
                JOptionPane.showMessageDialog(null, "El Nombre de Usuario o la Contraseña no son Correctos", "Error en las Credenciales", JOptionPane.ERROR_MESSAGE);
            }
        }
    }    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextUser = new rojeru_san.RSMTextFull();
        TextPassword = new rojeru_san.RSMPassView();
        BtnAcceso = new rojeru_san.RSButton();
        JLogo = new javax.swing.JLabel();
        JTitulo = new javax.swing.JLabel();
        JInfoWarning = new javax.swing.JLabel();
        JInfoError = new javax.swing.JLabel();
        BtnSalir = new rojeru_san.RSButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TextUser.setBackground(new java.awt.Color(255, 255, 255));
        TextUser.setForeground(new java.awt.Color(51, 51, 51));
        TextUser.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        TextUser.setBotonColor(new java.awt.Color(255, 255, 255));
        TextUser.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        TextUser.setPlaceholder("Ingresa tu usuario......");
        TextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUserActionPerformed(evt);
            }
        });
        TextUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextUserKeyPressed(evt);
            }
        });

        TextPassword.setBackground(new java.awt.Color(255, 255, 255));
        TextPassword.setForeground(new java.awt.Color(51, 51, 51));
        TextPassword.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        TextPassword.setBotonColor(new java.awt.Color(255, 255, 255));
        TextPassword.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        TextPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextPasswordKeyPressed(evt);
            }
        });

        BtnAcceso.setBackground(new java.awt.Color(0, 153, 255));
        BtnAcceso.setBorder(null);
        BtnAcceso.setText("Acceder a Plataforma");
        BtnAcceso.setColorHover(new java.awt.Color(9, 96, 158));
        BtnAcceso.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        BtnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccesoActionPerformed(evt);
            }
        });

        JLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logo-Selgesur-300px.png"))); // NOI18N

        JTitulo.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        JTitulo.setForeground(new java.awt.Color(255, 255, 255));
        JTitulo.setText("Plataforma de Gestión");

        JInfoWarning.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JInfoWarning.setForeground(new java.awt.Color(0, 102, 204));

        JInfoError.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        JInfoError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(JTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(JLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JTitulo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BtnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 850, 380));

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setText("X");
        BtnSalir.setColorHover(new java.awt.Color(153, 0, 0));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BackgroundLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUserActionPerformed

    private void BtnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccesoActionPerformed
        // TODO add your handling code here:
        iniciarSesion();
    }//GEN-LAST:event_BtnAccesoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        Functions Event = new Functions();
        Event.confirmarSalida();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TextUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextUserKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (a == KeyEvent.VK_ENTER) {
            TextPassword.requestFocus();
        }
    }//GEN-LAST:event_TextUserKeyPressed

    private void TextPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPasswordKeyPressed
        // TODO add your handling code here:
         char a = evt.getKeyChar();
        if (a == KeyEvent.VK_ENTER) {
            iniciarSesion();
        }
    }//GEN-LAST:event_TextPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton BtnAcceso;
    private rojeru_san.RSButton BtnSalir;
    private javax.swing.JLabel JInfoError;
    private javax.swing.JLabel JInfoWarning;
    private javax.swing.JLabel JLogo;
    private javax.swing.JLabel JTitulo;
    private rojeru_san.RSMPassView TextPassword;
    private rojeru_san.RSMTextFull TextUser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
